services: 
  database:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=gym
    volumes:
      - database:/var/lib/postgresql/data

volumes: 
  database: